### ISSUE TITLE
Carousel is not showing

### ISSUE THREAD

**Issue by poonam279** [cristianraiber/awie#2]
Carousel is not showing anywhere, it appears in customizer but not on the front page.
http://prntscr.com/f9z3vm http://prntscr.com/f9z47y
Also, there is a console error regarding slider JS http://prntscr.com/f9z4cz

**Comment by rodica-andronache** [comment]
@poonam279 for me it's working ok. I think it may be something related to your local instance and how the scripts loaded. For you, the slider script loaded before jquery, so adding here https://github.com/Codeinwp/awie/blob/master/functions.php#L64 a dependency of jquery like
wp_enqueue_script( 'awye-slider-init', get_stylesheet_directory_uri() .  '/js/slider-init.js', array('jquery'), true );
should fix all possible issues. As we can't add this right now, in the child theme, you can try that, and let me know if users report this error too.
